// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_grpc.proto

package com.mycompany.proto.dto;

public final class TestGrpc {
  private TestGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_proto_dto_TestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_proto_dto_TestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mycompany_proto_dto_TestReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mycompany_proto_dto_TestReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017test_grpc.proto\022\027com.mycompany.proto.d" +
      "to\032\037google/protobuf/timestamp.proto\"\033\n\013T" +
      "estRequest\022\014\n\004name\030\001 \001(\t\"W\n\tTestReply\022\013\n" +
      "\003age\030\001 \001(\005\022/\n\013currentTIme\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\022\014\n\004name\030\003 \001(\t2i\n\017Tes" +
      "tPerformance\022V\n\010SayHello\022$.com.mycompany" +
      ".proto.dto.TestRequest\032\".com.mycompany.p" +
      "roto.dto.TestReply\"\000B\033\n\027com.mycompany.pr" +
      "oto.dtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_mycompany_proto_dto_TestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mycompany_proto_dto_TestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_proto_dto_TestRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_mycompany_proto_dto_TestReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mycompany_proto_dto_TestReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mycompany_proto_dto_TestReply_descriptor,
        new java.lang.String[] { "Age", "CurrentTIme", "Name", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
