// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_grpc.proto

package com.mycompany.proto.dto;

/**
 * Protobuf type {@code com.mycompany.proto.dto.TestReply}
 */
public  final class TestReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.mycompany.proto.dto.TestReply)
    TestReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TestReply.newBuilder() to construct.
  private TestReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TestReply() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TestReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TestReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            age_ = input.readInt32();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (currentTIme_ != null) {
              subBuilder = currentTIme_.toBuilder();
            }
            currentTIme_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentTIme_);
              currentTIme_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mycompany.proto.dto.TestGrpc.internal_static_com_mycompany_proto_dto_TestReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mycompany.proto.dto.TestGrpc.internal_static_com_mycompany_proto_dto_TestReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mycompany.proto.dto.TestReply.class, com.mycompany.proto.dto.TestReply.Builder.class);
  }

  public static final int AGE_FIELD_NUMBER = 1;
  private int age_;
  /**
   * <code>int32 age = 1;</code>
   * @return The age.
   */
  public int getAge() {
    return age_;
  }

  public static final int CURRENTTIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp currentTIme_;
  /**
   * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
   * @return Whether the currentTIme field is set.
   */
  public boolean hasCurrentTIme() {
    return currentTIme_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
   * @return The currentTIme.
   */
  public com.google.protobuf.Timestamp getCurrentTIme() {
    return currentTIme_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentTIme_;
  }
  /**
   * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCurrentTImeOrBuilder() {
    return getCurrentTIme();
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (age_ != 0) {
      output.writeInt32(1, age_);
    }
    if (currentTIme_ != null) {
      output.writeMessage(2, getCurrentTIme());
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (age_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, age_);
    }
    if (currentTIme_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCurrentTIme());
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mycompany.proto.dto.TestReply)) {
      return super.equals(obj);
    }
    com.mycompany.proto.dto.TestReply other = (com.mycompany.proto.dto.TestReply) obj;

    if (getAge()
        != other.getAge()) return false;
    if (hasCurrentTIme() != other.hasCurrentTIme()) return false;
    if (hasCurrentTIme()) {
      if (!getCurrentTIme()
          .equals(other.getCurrentTIme())) return false;
    }
    if (!getName()
        .equals(other.getName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge();
    if (hasCurrentTIme()) {
      hash = (37 * hash) + CURRENTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTIme().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mycompany.proto.dto.TestReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mycompany.proto.dto.TestReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mycompany.proto.dto.TestReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mycompany.proto.dto.TestReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mycompany.proto.dto.TestReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.mycompany.proto.dto.TestReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mycompany.proto.dto.TestReply)
      com.mycompany.proto.dto.TestReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mycompany.proto.dto.TestGrpc.internal_static_com_mycompany_proto_dto_TestReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mycompany.proto.dto.TestGrpc.internal_static_com_mycompany_proto_dto_TestReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mycompany.proto.dto.TestReply.class, com.mycompany.proto.dto.TestReply.Builder.class);
    }

    // Construct using com.mycompany.proto.dto.TestReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      age_ = 0;

      if (currentTImeBuilder_ == null) {
        currentTIme_ = null;
      } else {
        currentTIme_ = null;
        currentTImeBuilder_ = null;
      }
      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mycompany.proto.dto.TestGrpc.internal_static_com_mycompany_proto_dto_TestReply_descriptor;
    }

    @java.lang.Override
    public com.mycompany.proto.dto.TestReply getDefaultInstanceForType() {
      return com.mycompany.proto.dto.TestReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.mycompany.proto.dto.TestReply build() {
      com.mycompany.proto.dto.TestReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mycompany.proto.dto.TestReply buildPartial() {
      com.mycompany.proto.dto.TestReply result = new com.mycompany.proto.dto.TestReply(this);
      result.age_ = age_;
      if (currentTImeBuilder_ == null) {
        result.currentTIme_ = currentTIme_;
      } else {
        result.currentTIme_ = currentTImeBuilder_.build();
      }
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mycompany.proto.dto.TestReply) {
        return mergeFrom((com.mycompany.proto.dto.TestReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mycompany.proto.dto.TestReply other) {
      if (other == com.mycompany.proto.dto.TestReply.getDefaultInstance()) return this;
      if (other.getAge() != 0) {
        setAge(other.getAge());
      }
      if (other.hasCurrentTIme()) {
        mergeCurrentTIme(other.getCurrentTIme());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mycompany.proto.dto.TestReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mycompany.proto.dto.TestReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int age_ ;
    /**
     * <code>int32 age = 1;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }
    /**
     * <code>int32 age = 1;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 age = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      
      age_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp currentTIme_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> currentTImeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     * @return Whether the currentTIme field is set.
     */
    public boolean hasCurrentTIme() {
      return currentTImeBuilder_ != null || currentTIme_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     * @return The currentTIme.
     */
    public com.google.protobuf.Timestamp getCurrentTIme() {
      if (currentTImeBuilder_ == null) {
        return currentTIme_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentTIme_;
      } else {
        return currentTImeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     */
    public Builder setCurrentTIme(com.google.protobuf.Timestamp value) {
      if (currentTImeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentTIme_ = value;
        onChanged();
      } else {
        currentTImeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     */
    public Builder setCurrentTIme(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (currentTImeBuilder_ == null) {
        currentTIme_ = builderForValue.build();
        onChanged();
      } else {
        currentTImeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     */
    public Builder mergeCurrentTIme(com.google.protobuf.Timestamp value) {
      if (currentTImeBuilder_ == null) {
        if (currentTIme_ != null) {
          currentTIme_ =
            com.google.protobuf.Timestamp.newBuilder(currentTIme_).mergeFrom(value).buildPartial();
        } else {
          currentTIme_ = value;
        }
        onChanged();
      } else {
        currentTImeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     */
    public Builder clearCurrentTIme() {
      if (currentTImeBuilder_ == null) {
        currentTIme_ = null;
        onChanged();
      } else {
        currentTIme_ = null;
        currentTImeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCurrentTImeBuilder() {
      
      onChanged();
      return getCurrentTImeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCurrentTImeOrBuilder() {
      if (currentTImeBuilder_ != null) {
        return currentTImeBuilder_.getMessageOrBuilder();
      } else {
        return currentTIme_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : currentTIme_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp currentTIme = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCurrentTImeFieldBuilder() {
      if (currentTImeBuilder_ == null) {
        currentTImeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCurrentTIme(),
                getParentForChildren(),
                isClean());
        currentTIme_ = null;
      }
      return currentTImeBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.mycompany.proto.dto.TestReply)
  }

  // @@protoc_insertion_point(class_scope:com.mycompany.proto.dto.TestReply)
  private static final com.mycompany.proto.dto.TestReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mycompany.proto.dto.TestReply();
  }

  public static com.mycompany.proto.dto.TestReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TestReply>
      PARSER = new com.google.protobuf.AbstractParser<TestReply>() {
    @java.lang.Override
    public TestReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TestReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TestReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TestReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mycompany.proto.dto.TestReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

