// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_grpc.proto

package com.mycompany.proto.dto;

public interface TestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mycompany.proto.dto.TestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
